import type { DatabaseSync } from "node:sqlite";

const SCHEMA_VERSION = 1;

const BASELINE_TABLES = [
  "conversation_segments",
  "file_sync_operations",
  "idempotency_requests",
  "messages",
  "run_steps",
  "run_work_state",
  "runs",
  "schema_metadata",
  "session_attachments",
  "session_run_finalizations",
  "sessions",
  "simple_task_finalizations",
  "task_attachment_bindings",
  "task_mutation_authorities",
  "task_request_route_plans",
  "tasks",
] as const;

const BASELINE_SQL = [
  "CREATE TABLE schema_metadata (",
  "  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),",
  "  version INTEGER NOT NULL,",
  "  created_at TEXT NOT NULL",
  ");",
  "",
  "CREATE TABLE idempotency_requests (",
  "  request_id TEXT PRIMARY KEY,",
  "  operation TEXT NOT NULL,",
  "  request_hash TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('in_progress', 'completed', 'recovery_required')),",
  "  response_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  completed_at TEXT",
  ");",
  "",
  "CREATE TABLE sessions (",
  "  session_id TEXT PRIMARY KEY,",
  "  date TEXT NOT NULL,",
  "  timezone TEXT NOT NULL,",
  "  agent_id TEXT NOT NULL,",
  "  repository_path TEXT NOT NULL,",
  "  head_sha TEXT,",
  "  status TEXT NOT NULL CHECK (status IN ('open', 'rollover_pending', 'finalizing', 'sealed')),",
  "  previous_session_id TEXT REFERENCES sessions(session_id),",
  "  created_at TEXT NOT NULL,",
  "  sealed_at TEXT",
  ");",
  "CREATE UNIQUE INDEX sessions_one_live_per_agent",
  "ON sessions(agent_id)",
  "WHERE status IN ('open', 'rollover_pending', 'finalizing');",
  "",
  "CREATE TABLE tasks (",
  "  task_id TEXT PRIMARY KEY,",
  "  repository_path TEXT NOT NULL UNIQUE,",
  "  branch TEXT NOT NULL,",
  "  head_sha TEXT,",
  "  title_cache TEXT NOT NULL,",
  "  objective_cache TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('initializing', 'active', 'archived')),",
  "  created_session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX tasks_updated_at ON tasks(updated_at DESC);",
  "CREATE INDEX tasks_status ON tasks(status, updated_at DESC);",
  "",
  "CREATE TABLE conversation_segments (",
  "  conversation_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  sequence INTEGER NOT NULL,",
  "  file_path TEXT NOT NULL,",
  "  task_id TEXT REFERENCES tasks(task_id),",
  "  run_id TEXT,",
  "  status TEXT NOT NULL CHECK (status IN ('active', 'closed', 'committed')),",
  "  content_hash TEXT,",
  "  committed_sha TEXT,",
  "  started_at TEXT NOT NULL,",
  "  closed_at TEXT,",
  "  UNIQUE(session_id, sequence)",
  ");",
  "",
  "CREATE TABLE messages (",
  "  message_id TEXT PRIMARY KEY,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  session_sequence INTEGER NOT NULL,",
  "  segment_sequence INTEGER NOT NULL,",
  "  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system_event')),",
  "  content TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  UNIQUE(session_id, session_sequence),",
  "  UNIQUE(conversation_id, segment_sequence)",
  ");",
  "",
  "CREATE TABLE runs (",
  "  run_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  task_id TEXT REFERENCES tasks(task_id),",
  "  task_request_id TEXT,",
  "  run_sequence INTEGER NOT NULL,",
  "  run_class TEXT NOT NULL CHECK (run_class IN ('session', 'task')),",
  "  status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'blocked', 'needs_user_input')),",
  "  trigger TEXT NOT NULL CHECK (trigger IN ('user', 'system_event', 'internal')),",
  "  step_count INTEGER NOT NULL DEFAULT 0,",
  "  started_at TEXT NOT NULL,",
  "  completed_at TEXT,",
  "  UNIQUE(session_id, run_sequence)",
  ");",
  "CREATE UNIQUE INDEX runs_one_active_per_session",
  "ON runs(session_id)",
  "WHERE status = 'running';",
  "",
  "CREATE TABLE run_steps (",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  step INTEGER NOT NULL,",
  "  tool TEXT NOT NULL,",
  "  tool_schema_version INTEGER NOT NULL DEFAULT 1,",
  "  tool_effect TEXT NOT NULL CHECK (tool_effect IN ('read_only', 'mutating')),",
  "  purpose TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('completed', 'failed', 'blocked')),",
  "  input_json TEXT,",
  "  output_json TEXT,",
  "  output_hash TEXT,",
  "  verification_json TEXT,",
  "  created_at TEXT NOT NULL,",
  "  PRIMARY KEY(run_id, step)",
  ");",
  "",
  "CREATE TABLE run_work_state (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  revision INTEGER NOT NULL,",
  "  after_step INTEGER NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('not_done', 'done', 'blocked', 'needs_user_input')),",
  "  summary TEXT NOT NULL,",
  "  open_work_json TEXT NOT NULL,",
  "  blockers_json TEXT NOT NULL,",
  "  facts_json TEXT NOT NULL,",
  "  evidence_json TEXT NOT NULL,",
  "  artifacts_json TEXT NOT NULL,",
  "  next_step TEXT,",
  "  user_input_needed_json TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "",
  "CREATE TABLE file_sync_operations (",
  "  operation_id TEXT PRIMARY KEY,",
  "  request_id TEXT NOT NULL REFERENCES idempotency_requests(request_id) ON DELETE CASCADE,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  source_path TEXT,",
  "  target_path TEXT NOT NULL,",
  "  expected_content_hash TEXT,",
  "  status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'failed')),",
  "  created_at TEXT NOT NULL,",
  "  completed_at TEXT,",
  "  last_error TEXT",
  ");",
  "CREATE INDEX file_sync_operations_pending",
  "ON file_sync_operations(status, created_at);",
  "",
  "CREATE TABLE session_run_finalizations (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE REFERENCES idempotency_requests(request_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  phase TEXT NOT NULL CHECK (phase IN ('prepared', 'files_written', 'completed')),",
  "  run_file TEXT NOT NULL,",
  "  steps_file TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX session_run_finalizations_recovery",
  "ON session_run_finalizations(phase, updated_at);",
  "",
  "CREATE TABLE task_mutation_authorities (",
  "  authority_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  repository_path TEXT NOT NULL,",
  "  branch TEXT NOT NULL,",
  "  before_head TEXT NOT NULL,",
  "  lock_token_hash TEXT NOT NULL,",
  "  authorized_targets_json TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('active', 'verified', 'recovery_required', 'released')),",
  "  acquired_at TEXT NOT NULL,",
  "  expires_at TEXT NOT NULL,",
  "  verified_at TEXT,",
  "  released_at TEXT,",
  "  verification_json TEXT,",
  "  last_error TEXT",
  ");",
  "CREATE UNIQUE INDEX task_mutation_authorities_one_owner",
  "ON task_mutation_authorities(task_id)",
  "WHERE status IN ('active', 'verified', 'recovery_required');",
  "CREATE UNIQUE INDEX task_mutation_authorities_one_run",
  "ON task_mutation_authorities(run_id)",
  "WHERE status IN ('active', 'verified', 'recovery_required');",
  "",
  "CREATE TABLE simple_task_finalizations (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE REFERENCES idempotency_requests(request_id),",
  "  authority_id TEXT REFERENCES task_mutation_authorities(authority_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  phase TEXT NOT NULL CHECK (phase IN ('prepared', 'committed', 'completed', 'recovery_required')),",
  "  outcome TEXT NOT NULL CHECK (outcome IN ('done', 'incomplete', 'failed', 'blocked', 'needs_user_input')),",
  "  validation TEXT NOT NULL CHECK (validation IN ('passed', 'failed', 'not_run')),",
  "  summary TEXT NOT NULL,",
  "  next_action TEXT,",
  "  completion_json TEXT NOT NULL,",
  "  assistant_response TEXT NOT NULL,",
  "  base_head TEXT NOT NULL,",
  "  conversation_hash TEXT NOT NULL,",
  "  plan_json TEXT NOT NULL,",
  "  commit_head TEXT,",
  "  commit_created INTEGER NOT NULL DEFAULT 0 CHECK (commit_created IN (0, 1)),",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT",
  ");",
  "CREATE INDEX simple_task_finalizations_recovery",
  "ON simple_task_finalizations(phase, updated_at);",
  "",
  "CREATE TABLE session_attachments (",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  session_asset_id TEXT NOT NULL,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  attachment_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  PRIMARY KEY(conversation_id, session_asset_id)",
  ");",
  "CREATE INDEX session_attachments_recent",
  "ON session_attachments(session_id, updated_at DESC);",
  "",
  "CREATE TABLE task_attachment_bindings (",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  session_asset_id TEXT NOT NULL,",
  "  reference_id TEXT NOT NULL,",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  task_request_id TEXT NOT NULL,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  reference_json TEXT NOT NULL,",
  "  phase TEXT NOT NULL CHECK (phase IN ('placed', 'committed', 'recovery_required')),",
  "  commit_head TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT,",
  "  PRIMARY KEY(task_id, session_asset_id),",
  "  UNIQUE(task_id, reference_id)",
  ");",
  "CREATE INDEX task_attachment_bindings_run",
  "ON task_attachment_bindings(run_id, phase, reference_id);",
  "",
  "CREATE TABLE task_request_route_plans (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  base_head TEXT NOT NULL,",
  "  route_json TEXT NOT NULL,",
  "  change_plan_json TEXT,",
  "  phase TEXT NOT NULL CHECK (phase IN ('planned', 'authority_acquired', 'committed', 'discarded', 'recovery_required')),",
  "  authority_id TEXT REFERENCES task_mutation_authorities(authority_id),",
  "  commit_head TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT",
  ");",
  "CREATE UNIQUE INDEX task_request_route_plans_active_task",
  "ON task_request_route_plans(task_id)",
  "WHERE phase IN ('planned', 'authority_acquired', 'recovery_required');",
  "CREATE INDEX task_request_route_plans_recovery",
  "ON task_request_route_plans(phase, updated_at);",
].join("\n");

export function initializeSchema(database: DatabaseSync, now: () => string): void {
  const existingTables = readTableNames(database);
  if (existingTables.length === 0) {
    database.exec("BEGIN IMMEDIATE");
    try {
      database.exec(BASELINE_SQL);
      database.prepare(
        "INSERT INTO schema_metadata(singleton, version, created_at) VALUES (1, ?, ?)",
      ).run(SCHEMA_VERSION, now());
      database.exec("COMMIT");
      return;
    } catch (error) {
      database.exec("ROLLBACK");
      throw error;
    }
  }

  const versions = existingTables.includes("schema_metadata")
    ? database.prepare("SELECT version FROM schema_metadata WHERE singleton = 1").all() as Array<{
        version: number;
      }>
    : [];
  const versionMatches = versions.length === 1
    && Number(versions[0]?.version) === SCHEMA_VERSION;
  const tablesMatch = JSON.stringify(existingTables) === JSON.stringify(BASELINE_TABLES);
  if (!versionMatches || !tablesMatch) {
    throw new Error([
      "Git Context database reset required.",
      "The configured database uses a pre-V1 or unsupported schema and was not modified.",
      "Back up or move the database explicitly, then restart Ayati to create the V1 baseline.",
    ].join(" "));
  }
}

export function latestSchemaVersion(): number {
  return SCHEMA_VERSION;
}

function readTableNames(database: DatabaseSync): string[] {
  const rows = database.prepare([
    "SELECT name FROM sqlite_schema",
    "WHERE type = 'table' AND name NOT LIKE 'sqlite_%'",
    "ORDER BY name",
  ].join(" ")).all() as Array<{ name: string }>;
  return rows.map((row) => row.name);
}
