import type { DatabaseSync } from "node:sqlite";

const SCHEMA_VERSION = 3;

const BASELINE_TABLES = [
  "conversation_segments",
  "idempotency_requests",
  "messages",
  "run_steps",
  "run_work_state",
  "runs",
  "schema_metadata",
  "session_attachments",
  "sessions",
  "task_accesses",
  "task_attachment_bindings",
  "task_finalizations",
  "task_mutation_authorities",
  "task_preferences",
  "task_registration_inspections",
  "task_request_route_plans",
  "task_search",
  "tasks",
  "unbound_run_finalizations",
] as const;

const BASELINE_SQL = [
  "CREATE TABLE schema_metadata (",
  "  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),",
  "  version INTEGER NOT NULL,",
  "  created_at TEXT NOT NULL",
  ");",
  "",
  "CREATE TABLE idempotency_requests (",
  "  request_id TEXT PRIMARY KEY,",
  "  operation TEXT NOT NULL,",
  "  request_hash TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('in_progress', 'completed', 'recovery_required')),",
  "  response_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  completed_at TEXT",
  ");",
  "",
  "CREATE TABLE sessions (",
  "  session_id TEXT PRIMARY KEY,",
  "  date TEXT NOT NULL,",
  "  timezone TEXT NOT NULL,",
  "  agent_id TEXT NOT NULL,",
  "  repository_path TEXT NOT NULL,",
  "  head_sha TEXT,",
  "  status TEXT NOT NULL CHECK (status IN ('open', 'rollover_pending', 'finalizing', 'sealed')),",
  "  previous_session_id TEXT REFERENCES sessions(session_id),",
  "  created_at TEXT NOT NULL,",
  "  sealed_at TEXT",
  ");",
  "CREATE UNIQUE INDEX sessions_one_live_per_agent",
  "ON sessions(agent_id)",
  "WHERE status IN ('open', 'rollover_pending', 'finalizing');",
  "",
  "CREATE TABLE tasks (",
  "  task_id TEXT PRIMARY KEY,",
  "  repository_path TEXT NOT NULL UNIQUE,",
  "  branch TEXT NOT NULL,",
  "  head_sha TEXT,",
  "  title_cache TEXT NOT NULL,",
  "  objective_cache TEXT NOT NULL,",
  "  placement_mode TEXT NOT NULL DEFAULT 'managed' CHECK (placement_mode IN ('managed', 'requested')),",
  "  trusted_root TEXT NOT NULL DEFAULT '',",
  "  registration_head_before TEXT,",
  "  registration_was_git INTEGER NOT NULL DEFAULT 0 CHECK (registration_was_git IN (0, 1)),",
  "  registration_approval_id TEXT,",
  "  registration_snapshot_hash TEXT,",
  "  baseline_paths_json TEXT NOT NULL DEFAULT '[]',",
  "  registration_excluded_paths_json TEXT NOT NULL DEFAULT '[]',",
  "  lifecycle_status TEXT NOT NULL DEFAULT 'active' CHECK (lifecycle_status IN ('active', 'paused', 'archived')),",
  "  repository_health TEXT NOT NULL DEFAULT 'ready' CHECK (repository_health IN ('ready', 'dirty_external', 'unavailable')),",
  "  current_request_id TEXT,",
  "  current_request_title TEXT,",
  "  current_request_status TEXT CHECK (current_request_status IN ('queued', 'active', 'blocked', 'done', 'dropped')),",
  "  status TEXT NOT NULL CHECK (status IN ('initializing', 'active', 'archived')),",
  "  created_session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "CREATE INDEX tasks_updated_at ON tasks(updated_at DESC);",
  "CREATE INDEX tasks_status ON tasks(status, updated_at DESC);",
  "CREATE INDEX tasks_current_request ON tasks(current_request_status, updated_at DESC);",
  "",
  "CREATE TABLE task_preferences (",
  "  task_id TEXT PRIMARY KEY REFERENCES tasks(task_id) ON DELETE CASCADE,",
  "  starred INTEGER NOT NULL CHECK (starred IN (0, 1)),",
  "  starred_at TEXT,",
  "  updated_at TEXT NOT NULL,",
  "  CHECK ((starred = 1 AND starred_at IS NOT NULL) OR (starred = 0 AND starred_at IS NULL))",
  ");",
  "CREATE INDEX task_preferences_starred ON task_preferences(starred, starred_at DESC);",
  "",
  "CREATE TABLE task_accesses (",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,",
  "  access_kind TEXT NOT NULL CHECK (access_kind IN ('opened', 'bound')),",
  "  accessed_at TEXT NOT NULL,",
  "  PRIMARY KEY(task_id, run_id, access_kind)",
  ");",
  "CREATE INDEX task_accesses_recent ON task_accesses(task_id, accessed_at DESC);",
  "CREATE INDEX task_accesses_frequency ON task_accesses(access_kind, accessed_at DESC, task_id);",
  "",
  "CREATE VIRTUAL TABLE task_search USING fts5(",
  "  task_id UNINDEXED,",
  "  title,",
  "  objective,",
  "  current_request,",
  "  repository_path,",
  "  tokenize = 'unicode61 remove_diacritics 2'",
  ");",
  "",
  "CREATE TABLE conversation_segments (",
  "  conversation_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  sequence INTEGER NOT NULL,",
  "  file_path TEXT NOT NULL,",
  "  task_id TEXT REFERENCES tasks(task_id),",
  "  run_id TEXT,",
  "  status TEXT NOT NULL CHECK (status IN ('active', 'closed', 'committed')),",
  "  content_hash TEXT,",
  "  committed_sha TEXT,",
  "  started_at TEXT NOT NULL,",
  "  closed_at TEXT,",
  "  UNIQUE(session_id, sequence)",
  ");",
  "",
  "CREATE TABLE messages (",
  "  message_id TEXT PRIMARY KEY,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  session_sequence INTEGER NOT NULL,",
  "  segment_sequence INTEGER NOT NULL,",
  "  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system_event')),",
  "  content TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  UNIQUE(session_id, session_sequence),",
  "  UNIQUE(conversation_id, segment_sequence)",
  ");",
  "",
  "CREATE TABLE runs (",
  "  run_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  task_id TEXT REFERENCES tasks(task_id),",
  "  task_request_id TEXT,",
  "  task_bound_at TEXT,",
  "  run_sequence INTEGER NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('running', 'done', 'incomplete', 'failed', 'blocked', 'needs_user_input', 'recovery_required')),",
  "  stop_reason TEXT CHECK (stop_reason IN ('completed', 'run_limit', 'context_limit', 'failed', 'blocked', 'needs_user_input', 'interrupted')),",
  "  trigger TEXT NOT NULL CHECK (trigger IN ('user', 'system_event', 'internal')),",
  "  step_count INTEGER NOT NULL DEFAULT 0,",
  "  started_at TEXT NOT NULL,",
  "  completed_at TEXT,",
  "  CHECK ((task_id IS NULL AND task_request_id IS NULL AND task_bound_at IS NULL)",
  "    OR (task_id IS NOT NULL AND task_request_id IS NOT NULL AND task_bound_at IS NOT NULL)),",
  "  CHECK ((status IN ('running', 'recovery_required') AND stop_reason IS NULL AND completed_at IS NULL)",
  "    OR (status = 'done' AND stop_reason = 'completed' AND completed_at IS NOT NULL)",
  "    OR (status = 'failed' AND stop_reason = 'failed' AND completed_at IS NOT NULL)",
  "    OR (status = 'blocked' AND stop_reason = 'blocked' AND completed_at IS NOT NULL)",
  "    OR (status = 'needs_user_input' AND stop_reason = 'needs_user_input' AND completed_at IS NOT NULL)",
  "    OR (status = 'incomplete' AND stop_reason IN ('run_limit', 'context_limit', 'interrupted') AND completed_at IS NOT NULL)),",
  "  UNIQUE(session_id, run_sequence)",
  ");",
  "CREATE UNIQUE INDEX runs_one_active_per_session",
  "ON runs(session_id)",
  "WHERE status IN ('running', 'recovery_required');",
  "CREATE TRIGGER runs_task_binding_immutable",
  "BEFORE UPDATE OF task_id, task_request_id, task_bound_at ON runs",
  "WHEN OLD.task_id IS NOT NULL AND (NEW.task_id IS NOT OLD.task_id",
  "  OR NEW.task_request_id IS NOT OLD.task_request_id",
  "  OR NEW.task_bound_at IS NOT OLD.task_bound_at)",
  "BEGIN SELECT RAISE(ABORT, 'run task binding is immutable'); END;",
  "",
  "CREATE TABLE run_steps (",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  step INTEGER NOT NULL,",
  "  record_version INTEGER NOT NULL CHECK (record_version = 1),",
  "  status TEXT NOT NULL CHECK (status IN ('completed', 'failed', 'blocked')),",
  "  summary TEXT NOT NULL,",
  "  decision_json TEXT,",
  "  action_json TEXT,",
  "  tool_calls_json TEXT NOT NULL,",
  "  verification_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  PRIMARY KEY(run_id, step)",
  ");",
  "",
  "CREATE TABLE run_work_state (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  revision INTEGER NOT NULL,",
  "  after_step INTEGER NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('not_done', 'done', 'blocked', 'needs_user_input')),",
  "  summary TEXT NOT NULL,",
  "  open_work_json TEXT NOT NULL,",
  "  blockers_json TEXT NOT NULL,",
  "  facts_json TEXT NOT NULL,",
  "  evidence_json TEXT NOT NULL,",
  "  artifacts_json TEXT NOT NULL,",
  "  next_step TEXT,",
  "  user_input_needed_json TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL",
  ");",
  "",
  "CREATE TABLE unbound_run_finalizations (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE REFERENCES idempotency_requests(request_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  phase TEXT NOT NULL CHECK (phase IN ('prepared', 'files_written', 'completed', 'recovery_required')),",
  "  outcome TEXT NOT NULL CHECK (outcome IN ('done', 'incomplete', 'failed', 'blocked', 'needs_user_input')),",
  "  stop_reason TEXT NOT NULL CHECK (stop_reason IN ('completed', 'run_limit', 'context_limit', 'failed', 'blocked', 'needs_user_input', 'interrupted')),",
  "  materialization_requested INTEGER NOT NULL CHECK (materialization_requested IN (0, 1)),",
  "  run_file TEXT,",
  "  steps_file TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT",
  ");",
  "CREATE INDEX unbound_run_finalizations_recovery",
  "ON unbound_run_finalizations(phase, updated_at);",
  "",
  "CREATE TABLE task_mutation_authorities (",
  "  authority_id TEXT PRIMARY KEY,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  repository_path TEXT NOT NULL,",
  "  branch TEXT NOT NULL,",
  "  before_head TEXT NOT NULL,",
  "  lock_token_hash TEXT NOT NULL,",
  "  authorized_targets_json TEXT NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('active', 'verified', 'recovery_required', 'released')),",
  "  acquired_at TEXT NOT NULL,",
  "  expires_at TEXT NOT NULL,",
  "  verified_at TEXT,",
  "  released_at TEXT,",
  "  verification_json TEXT,",
  "  last_error TEXT",
  ");",
  "CREATE UNIQUE INDEX task_mutation_authorities_one_owner",
  "ON task_mutation_authorities(task_id)",
  "WHERE status IN ('active', 'verified', 'recovery_required');",
  "CREATE UNIQUE INDEX task_mutation_authorities_one_run",
  "ON task_mutation_authorities(run_id)",
  "WHERE status IN ('active', 'verified', 'recovery_required');",
  "",
  "CREATE TABLE task_finalizations (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE REFERENCES idempotency_requests(request_id),",
  "  authority_id TEXT REFERENCES task_mutation_authorities(authority_id),",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  phase TEXT NOT NULL CHECK (phase IN ('prepared', 'committed', 'completed', 'recovery_required')),",
  "  outcome TEXT NOT NULL CHECK (outcome IN ('done', 'incomplete', 'failed', 'blocked', 'needs_user_input')),",
  "  stop_reason TEXT NOT NULL CHECK (stop_reason IN ('completed', 'run_limit', 'context_limit', 'failed', 'blocked', 'needs_user_input', 'interrupted')),",
  "  validation TEXT NOT NULL CHECK (validation IN ('passed', 'failed', 'not_applicable')),",
  "  summary TEXT NOT NULL,",
  "  next_action TEXT,",
  "  completion_json TEXT NOT NULL,",
  "  assistant_response TEXT NOT NULL,",
  "  base_head TEXT NOT NULL,",
  "  conversation_hash TEXT NOT NULL,",
  "  plan_json TEXT NOT NULL,",
  "  commit_head TEXT,",
  "  commit_created INTEGER NOT NULL DEFAULT 0 CHECK (commit_created IN (0, 1)),",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT",
  ");",
  "CREATE INDEX task_finalizations_recovery",
  "ON task_finalizations(phase, updated_at);",
  "",
  "CREATE TABLE session_attachments (",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  session_asset_id TEXT NOT NULL,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  attachment_json TEXT NOT NULL,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  PRIMARY KEY(conversation_id, session_asset_id)",
  ");",
  "CREATE INDEX session_attachments_recent",
  "ON session_attachments(session_id, updated_at DESC);",
  "",
  "CREATE TABLE task_attachment_bindings (",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  session_asset_id TEXT NOT NULL,",
  "  reference_id TEXT NOT NULL,",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  task_request_id TEXT NOT NULL,",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  reference_json TEXT NOT NULL,",
  "  phase TEXT NOT NULL CHECK (phase IN ('placed', 'committed', 'recovery_required')),",
  "  commit_head TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT,",
  "  PRIMARY KEY(task_id, session_asset_id),",
  "  UNIQUE(task_id, reference_id)",
  ");",
  "CREATE INDEX task_attachment_bindings_run",
  "ON task_attachment_bindings(run_id, phase, reference_id);",
  "",
  "CREATE TABLE task_request_route_plans (",
  "  run_id TEXT PRIMARY KEY REFERENCES runs(run_id),",
  "  request_id TEXT NOT NULL UNIQUE,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  task_id TEXT NOT NULL REFERENCES tasks(task_id),",
  "  task_request_id TEXT NOT NULL,",
  "  base_head TEXT NOT NULL,",
  "  route_json TEXT NOT NULL,",
  "  change_plan_json TEXT,",
  "  phase TEXT NOT NULL CHECK (phase IN ('planned', 'authority_acquired', 'committed', 'discarded', 'recovery_required')),",
  "  authority_id TEXT REFERENCES task_mutation_authorities(authority_id),",
  "  commit_head TEXT,",
  "  created_at TEXT NOT NULL,",
  "  updated_at TEXT NOT NULL,",
  "  last_error TEXT",
  ");",
  "CREATE UNIQUE INDEX task_request_route_plans_active_task",
  "ON task_request_route_plans(task_id)",
  "WHERE phase IN ('planned', 'authority_acquired', 'recovery_required');",
  "CREATE INDEX task_request_route_plans_recovery",
  "ON task_request_route_plans(phase, updated_at);",
  "",
  "CREATE TABLE task_registration_inspections (",
  "  inspection_id TEXT PRIMARY KEY,",
  "  request_id TEXT NOT NULL UNIQUE,",
  "  session_id TEXT NOT NULL REFERENCES sessions(session_id),",
  "  conversation_id TEXT NOT NULL REFERENCES conversation_segments(conversation_id),",
  "  run_id TEXT NOT NULL REFERENCES runs(run_id),",
  "  canonical_path TEXT NOT NULL,",
  "  trusted_root TEXT NOT NULL,",
  "  snapshot_hash TEXT NOT NULL,",
  "  proposed_paths_json TEXT NOT NULL,",
  "  excluded_paths_json TEXT NOT NULL,",
  "  entry_count INTEGER NOT NULL,",
  "  total_bytes INTEGER NOT NULL,",
  "  status TEXT NOT NULL CHECK (status IN ('pending', 'consumed', 'expired')),",
  "  created_at TEXT NOT NULL,",
  "  expires_at TEXT NOT NULL,",
  "  consumed_at TEXT",
  ");",
  "CREATE INDEX task_registration_inspections_pending",
  "ON task_registration_inspections(status, expires_at);",
].join("\n");

export function initializeSchema(database: DatabaseSync, now: () => string): void {
  const existingTables = readTableNames(database);
  if (existingTables.length === 0) {
    database.exec("BEGIN IMMEDIATE");
    try {
      database.exec(BASELINE_SQL);
      database.prepare(
        "INSERT INTO schema_metadata(singleton, version, created_at) VALUES (1, ?, ?)",
      ).run(SCHEMA_VERSION, now());
      database.exec("COMMIT");
      return;
    } catch (error) {
      database.exec("ROLLBACK");
      throw error;
    }
  }

  const versions = existingTables.includes("schema_metadata")
    ? database.prepare("SELECT version FROM schema_metadata WHERE singleton = 1").all() as Array<{
        version: number;
      }>
    : [];
  const versionMatches = versions.length === 1
    && Number(versions[0]?.version) === SCHEMA_VERSION;
  const tablesMatch = JSON.stringify(existingTables) === JSON.stringify(BASELINE_TABLES);
  if (!versionMatches || !tablesMatch) {
    throw new Error([
      "Git Context database reset required.",
      "The configured database uses a pre-V3 or unsupported schema and was not modified.",
      "Run context:archive-reset explicitly, then restart Ayati to create the V3 baseline.",
    ].join(" "));
  }
}

export function latestSchemaVersion(): number {
  return SCHEMA_VERSION;
}

function readTableNames(database: DatabaseSync): string[] {
  const rows = database.prepare([
    "SELECT name FROM sqlite_schema",
    "WHERE type = 'table' AND name NOT LIKE 'sqlite_%'",
    "AND name NOT GLOB 'task_search_*'",
    "ORDER BY name",
  ].join(" ")).all() as Array<{ name: string }>;
  return rows.map((row) => row.name);
}
