export type ContextEngineErrorCode =
  | "INVALID_REQUEST"
  | "NOT_FOUND"
  | "IDEMPOTENCY_CONFLICT"
  | "SERVICE_NOT_READY"
  | "AGENT_STREAM_NOT_FOUND"
  | "CHECKPOINT_NOT_REQUIRED"
  | "CHECKPOINT_SOURCE_CHANGED"
  | "CHECKPOINT_INVALID"
  | "CONTEXT_REVISION_MISMATCH"
  | "HISTORY_REF_INVALID"
  | "WORKSTREAM_NOT_FOUND"
  | "WORKSTREAM_SCHEMA_UNSUPPORTED"
  | "WORKSTREAM_CARD_INVALID"
  | "WORKSTREAM_ID_MISMATCH"
  | "WORKSTREAM_REQUEST_INVALID"
  | "WORKSTREAM_REQUEST_STATE_INVALID"
  | "WORKSTREAM_CURRENT_REQUEST_INVALID"
  | "WORKSTREAM_REPOSITORY_INVALID"
  | "WORKSTREAM_REPOSITORY_DIRTY"
  | "WORKSTREAM_BUSY"
  | "WORKSTREAM_LOCKED"
  | "WORKSTREAM_CHECKOUT_DIRTY"
  | "WORKSTREAM_HEAD_MISMATCH"
  | "WORKSTREAM_RESOLUTION_NOT_FOUND"
  | "RUN_NOT_ACTIVE"
  | "RUN_ALREADY_ACTIVE"
  | "RUN_ALREADY_FINALIZED"
  | "RUN_WORKSTREAM_BINDING_IMMUTABLE"
  | "RUN_STEP_NOT_CONTIGUOUS"
  | "MUTATION_REQUIRES_WORKSTREAM_BINDING"
  | "RUN_WORKSTREAM_BINDING_REQUIRED"
  | "RESOURCE_NOT_FOUND"
  | "RESOURCE_CONFLICT"
  | "RESOURCE_BINDING_INVALID"
  | "RESOURCE_LOCATOR_INVALID"
  | "RESOURCE_METADATA_INVALID"
  | "RESOURCE_STORE_CORRUPT"
  | "RESOURCE_MUTATION_UNAVAILABLE"
  | "RESOURCE_MUTATION_NOT_FOUND"
  | "RESOURCE_VERSION_MISMATCH"
  | "RESOURCE_VERIFICATION_UNAVAILABLE"
  | "MUTATION_TARGET_INVALID"
  | "MUTATION_LOCK_INVALID"
  | "MUTATION_AUTHORITY_CONFLICT"
  | "UNKNOWN_TOOL_CLASSIFICATION"
  | "REPOSITORY_UNAVAILABLE"
  | "GIT_CONFLICT"
  | "RECOVERY_REQUIRED"
  | "INTERNAL_ERROR";

export class ContextEngineServiceError extends Error {
  readonly code: ContextEngineErrorCode;
  readonly retryable: boolean;
  readonly details?: Record<string, unknown>;

  constructor(input: {
    code: ContextEngineErrorCode;
    message: string;
    retryable?: boolean;
    details?: Record<string, unknown>;
  }) {
    super(input.message);
    this.name = "ContextEngineServiceError";
    this.code = input.code;
    this.retryable = input.retryable ?? false;
    this.details = input.details;
  }

}
